### ISSUE TITLE
Issue with recast navigation dependency using premake5

### ISSUE THREAD

**Issue by dlee640** [ori-drs/recast_ros#15]
Hello. Thank you very much for great work! I am trying to replicate gaitmesh, thus came to this repo to take care of the dependencies.

I successfully built recast navigation on my Ubuntu 20.04 using `premake5`, as specified by the instructions on https://github.com/recastnavigation/recastnavigation. However, when I try to `catkin build` my gaitmesh workspace, it generates an error looking for `recast_navigationConfig.cmake`. It seems that `recastnavigation` repo doesn't officially support build option using cmake, so I wanted to ask how you handled this issue.

Your help would be appreciated.

Danny
![Screenshot from 2021-10-25 16-33-57](https://user-images.githubusercontent.com/60672433/138766776-ad325c1b-6bed-4c63-9fc7-f709ed7254fe.png)

**Comment by wxmerkt** [comment]
Hi Danny,
Thank you for your interest in our work. Did you use our fork for recastnavigation (https://github.com/ori-drs/recastnavigation)? It's a catkinised version that should work - and no need for premake5

Best wishes,
Wolfgang

**Comment by dlee640** [comment]
Thank you Wolfgang. The issue has been resolved.

Best,

Danny

**Comment by Joyuan-sys** [comment]
Hello,  I have succeed in catkin build. Gaitmesh ,recast_ros and recastnavigation are OK. However, I  "roslaunch recast_demos test_input_map.launch" It does not work and exit as you can see in the photo. What is the problem?
![erro](https://user-images.githubusercontent.com/72717363/149889196-fd1a3fa5-0763-4204-9039-d77d590d9dc4.png)

Your help would be appreciated
Joyuan
